TEAM_DICT = {'TB' : 'Tampa Bay Buccaneers',
             'SEA' : 'Seattle Seahawks',
             'SF' : 'San Francisco 49ers',
             'LAC' : 'Los Angelos Chargers',
             'PIT' : 'Pittsburgh Steelers',
             'ARI' : 'Arizona Cardinals',
             'PHI' : 'Philadelphia Eagles',
             'NYJ' : 'New York Jets',
             'NYG' : 'New York Giants',
             'NO' : 'New Orleans Saints',
             'NE' : 'New England Patriots',
             'MIN' : 'Minnesota Vikings',
             'MIA' : 'Miami Dolphins',
             'LV' : 'Las Vegas Raiders',
             'LAR' : 'Las Angelos Rams',
             'KC' : 'Kansas City Chiefs',
             'JAX' : 'Jacksonville Jaguars',
             'IND' : 'Indianapolis Colts',
             'TEN' : 'Tennessee Titans',
             'GB' : 'Green Bay Packers',
             'DET' : 'Detroit Lions',
             'DEN' : 'Denver Broncos',
             'DAL' : 'Dallas Cowboys',
             'CLE' : 'Cleveland Browns',
             'CIN' : 'Cincinnati Bengals',
             'CHI' : 'Chicago Bears',
             'CAR' : 'Carolina Panthers',
             'BUF' : 'Buffalo Bills',
             'BAL' : 'Baltimore Ravens',
             'ATL' : 'Atlanta Falcons',
             'WAS' : 'Washington Commanders',
             'HOU' : 'Houston Texans'
    }